---
ID: "143c02e9-41e5-4803-a702-42d3bf01c141"
Parent: "0faa6199-bb54-455b-bacc-3b018c3fac1e"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/content/uniform-jss/Home/About/local"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: business/16x16/index.png
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Local Page Content
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200304T235806Z
